version: "3.3"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: nextcloud
    ports:
      - 8080:80
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    depends_on:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db_data:
  nextcloud_data:
